### ISSUE TITLE
Tracking issue : W3F Grants Milestone 1

### ISSUE THREAD

**Issue by stanly-johnson** [virto-network/virto-node#130]
Refer : https://github.com/w3f/Grants-Program/blob/master/applications/plip.md

- [x] Switch from assets pallet to tokens pallet (#129)
- [x] Update xcm and xtokens support (#132)
- [x] Add benchmarks for escrow pallet (#155)
~- [ ] Add benchmarks for rates pallet~ (removed in #131)
- [ ] Launch public testnet and update README on how to create local version / access testnet
