### ISSUE TITLE
Rococo checklist

### ISSUE THREAD

**Issue by olanod** [virto-network/virto-node#194]
Rococo being the defacto testnet for parachains is important that we test and deploy our chain in that environment to run all kinds of integration tests including cross-chain transfers.

- [ ] Publish updated docker image in GH registry
- [ ] Deploy at least one testnet collator
- [ ] Chain on-boarding and produce blocks
- [ ] Test payments pallet
- [ ] Test x-chain transfers*
