### ISSUE TITLE
Rococo deployment checklist and testing plan.

### ISSUE THREAD

**Issue by darkforest0202** [virto-network/virto-node#271]
This issue documents all the necessary steps to conduct the deployment and testing on Rococo.

## Deployment

- [ ] Benchmarks preparation: Review which pallets are being benchmarked and update `WeightInfo`.
- [ ] Run benchmarking and create new `weights.rs` files. https://github.com/virto-network/virto-node/issues/275
- [ ] Deploy two collators for Rococo and wait until the relay chain node gets fully sync.
- [ ] Get slot on Rococo (#243)
- [ ] Update PARA ID 4265
- [ ] Wait until parachain is onboarded.
- [ ] Change this line to Rococo on `xcm_config.rs` :

`GlobalConsensus(NetworkId::Kusama)`

## Testing

- [ ] Runtime upgrade from seedling to kreivo.
- [ ] Disable transaction filters.
- [ ] Create USDT asset (id 1984)
- [ ] Reserve transfer ROC from relay chain to the parachain.
- [ ] Burn the fake initial supply (in the parachain they will appear as KSM)
- [ ] Reserve transfer USDT from rockmine to kreivo.

Deployment and testing plan is still in progress.

**Comment by darkforest0202** [comment]
@olanod  can we close this one? maybe is not necessary anymore...
